CREATE VIEW getSite AS SELECT * FROM duck_shop;
CREATE VIEW productlist AS SELECT * FROM products;

CREATE PROCEDURE `getFooter`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER SELECT * FROM duck_shop;
CREATE PROCEDURE `getProducts`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER SELECT * FROM duck_shop;
